# Usa imagem oficial do Java 17
FROM eclipse-temurin:17-jdk

# Define o diretório de trabalho no container
WORKDIR /app

# Copia o JAR gerado pelo Maven


# Executa o JAR
ENTRYPOINT ["java", "-jar", "app.jar"]

